### ISSUE TITLE
Process bazelcommitlog

### ISSUE THREAD

**Issue by pmop** [Nimrod-Easy-Lab/annotations_repos#1]
Analyze bazelcommitlog and append relevant bugfixes/changes involving annotations.

**Comment by jcarlosadm** [comment]
commit d22e1dea7aa6135baceee18c6eac23a7d1b3c18e

See https://github.com/bazelbuild/bazel/commit/d22e1dea7aa6135baceee18c6eac23a7d1b3c18e
related issue: https://github.com/bazelbuild/bazel/issues/3714

Incorrect use:
`@ParamType(type = SkylarkList.class, generic1 = String.class)`
Correct one:
`@ParamType(type = Iterable.class, generic1 = String.class)`

Import:
`import com.google.devtools.build.lib.skylarkinterface.ParamType;`

**Comment by jcarlosadm** [comment]
see [5d30e251c43e18247ed8857ff60df9c3454a120b](https://github.com/Nimrod-Easy-Lab/annotations_repos/commit/5d30e251c43e18247ed8857ff60df9c3454a120b)
