### ISSUE TITLE
Process elasticsearchcommitlog

### ISSUE THREAD

**Issue by pmop** [Nimrod-Easy-Lab/annotations_repos#2]
Analyze elasticsearchcommitlog and append relevant bugfixes/changes involving annotations.

**Comment by jcarlosadm** [comment]
commit 204df2a1991f7e5f676d43fa6986b7c02f0a6d52

fix @TestLogging annotation

Incorrect use:
`@TestLogging("_root:DEBUGorg.elasticsearch.action.bulk:TRACE,org.elasticsearch.index.shard:TRACE,org.elasticsearch.cluster.service:TRACE")`
Correct one:
`@TestLogging("_root:DEBUG,org.elasticsearch.action.bulk:TRACE,org.elasticsearch.index.shard:TRACE,org.elasticsearch.cluster.service:TRACE")`
