### ISSUE TITLE
analyzing elasticsearch project

### ISSUE THREAD

**Issue by jcarlosadm** [Nimrod-Easy-Lab/annotations_repos#27]

**Comment by pmop** [comment]
Candidates:
https://github.com/elastic/elasticsearch/commit/2bd09c4625898d77aa6c015c6f82cf973ed18cb7
File: https://github.com/elastic/elasticsearch/commit/2bd09c4625898d77aa6c015c6f82cf973ed18cb7
`@Nullable -> [ ]`

**Comment by pmop** [comment]
[ ] -> @ClusterDynamicSettings
